// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omeimrnloozvvpdcsfnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tZWltcm5sb296dnZwZGNzZm5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzg0MjYsImV4cCI6MjA2NDYxNDQyNn0.ep9-a6tVLJcJc8kD8Qys-8Vb88hi28dI9b0khfIu9K4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);